### ISSUE TITLE
Quick Question - Iris

### ISSUE THREAD

**Issue by brianschardt** [carletes/mock-ssh-server#20]
Hey I have founded a company called Iris, which is an app that notifies your friends every time you make a trade on Robinhood, or whatever broker you use. We are VC-backed and have 9 engineers. We are looking to hire a python engineer. We were building out a python monorepo and found one of your repos.

Do you have time for a 30 min call?

**Comment by TitaniumHocker** [comment]
This section is not a place for spam. If you have no questions about this package, then I close this issue.
